---

- hosts: all
  become: true
  tasks:

  - name: "Update repository index"
    dnf:
      update_cache: yes
    when: ansible_distribution in ["CentOS", "RedHat"]

  - name: "Install Apache"
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS" 
