---

- hosts: all
  become: true
  tasks:

  - name: "Install updates for CentOS"
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"


  - name: "Install updates for Ubuntu"
    apt: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Ubuntu"     


- hosts: web_servers
  become: true
  tasks: 


  - name: "Install Apache and PHP for Ubuntu"
    apt: 
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: "Install Apache and PHP for Centos"
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
      
